### ISSUE TITLE
Undefined variable: quotes

### ISSUE THREAD

**Issue by maurisource** [flagshipcompany/flagship-for-magento#5]
I've done this config according to the documentation:

> 
> Under FlagShip Configuration, set the API Token, Packing and Logging preferences.
> Make sure that Store Address is set under Store > Configuration > General > Store Information
> Every source should be assigned an address. You can set it: Store > Sources > (Edit the source) > Address Data
> Enable the shipping methods, Store > Configuration > Sales > Shipping Methods > FlagShip Shipping

This is on vanilla Magento 2.3.2 CE

I get this error when creating an order in Sales > Order and clicking "Get Rates"

Notice: Undefined variable: quotes in /vendor/flagshipcompany/flagship-for-magento/Model/Carrier/FlagshipQuote.php on line 204

**Comment by maurisource** [comment]
This bug request is now pending for more than 14 days. Also contacted support via email with no avail which brings me to believe that FLAGSHIP is not an ongoin supported product while they are still charging for their services.

**Comment by radua** [comment]
Hi @maurisource . Kindly update your installation of flagship-for-magento to the latest version. If you still face this error, kindly share the logs and a screenshot. Thanks!

**Comment by maurisource** [comment]
@radua Pulled the latest version 1.0.36. The error reported above is not seen anymore, but there's still no rates shown on order creation page. 

I'm using the Live key, and set Test environment to NO.

What is the issue here?


Flagship.log
```
[2020-05-05 20:57:56] Flagship.INFO: Retrieved quotes from FlagShip [] []
[2020-05-05 20:57:56] Flagship.INFO: Prepared distribution method [] []
[2020-05-05 21:02:04] Flagship.INFO: Retrieved available services from FlagShip. Response Code : 200 [] []

```

**Comment by radua** [comment]
@maurisource Did you set an address for the store or the source? If not, please set the correct address for the source. If you are using just one source i.e. the default source, please update the address for the same. Also, please clear all Flagship logs and try placing an order again.
