### ISSUE TITLE
Crash Setting page after installation 

### ISSUE THREAD

**Issue by baldhadhaval08** [flagshipcompany/flagship-for-magento#6]
I followed these steps to integrate flag ship. 

> 

    Under FlagShip Configuration, set the API Token, Packing and Logging preferences.
    Make sure that Store Address is set under Store > Configuration > General > Store Information
    Every source should be assigned an address. You can set it: Store > Sources > (Edit the source) > Address Data
    Enable the shipping methods, Store > Configuration > Sales > Shipping Methods > FlagShip Shipping

But when I go in Store > Configuration > Sales > Shipping Methods then I'm getting error `Error: Cannot instantiate interface`
![image](https://user-images.githubusercontent.com/36040948/152300168-488ac2cd-215a-4ee3-ac4a-157bfed9942d.png)

**Comment by radua** [comment]
Can you please share your version of Magento. Also, please try running the following commands

bin/magento setup:upgrade;
 bin/magento setup:di:compile;
 bin/magento setup:static-content:deploy -f; 
bin/magento indexer:reindex;
bin/magento cache:clean

**Comment by baldhadhaval08** [comment]
@radua 
Magento version :  2.4.2
Yes I run all these commands. but still getting same error.
![image](https://user-images.githubusercontent.com/36040948/152528101-5e99e81e-288b-42af-bf24-c0952efc428f.png)

**Comment by radua** [comment]
Can you please send the token you are using to developers@flagshipcompany.com. Thanks

**Comment by baldhadhaval08** [comment]
> Can you please send the token you are using to [developers@flagshipcompany.com](mailto:developers@flagshipcompany.com). Thanks

I sent you token on that email.

**Comment by radua** [comment]
Please note that the current version of the plugin works with MSI, if you have disabled MSI, please use version 1.0.14
